volumes:
  postgres-data:

services:
  api:
    build: .
    container_name: api
    restart: always
    volumes:
      - ./migrations:/app/migrations
      - ./seeds:/app/seeds
      - ./src:/app/src
    ports:
      - 8080:8080
    depends_on:
      - postgres
      - trino1
      - trino2
      - trino3
    environment:
      - DB_URL=postgres://trino_proxy:trino_proxy@postgres/trino_proxy
      - HTTP_ENABLED=true
      - LOG_LEVEL=debug
      - NODE_ENV=production
      - ENABLE_API=true

  scheduler:
    build: .
    container_name: scheduler
    restart: always
    volumes:
      - ./src:/app/src
    ports:
      - 8081:8080
    depends_on:
      - postgres
      - trino1
      - trino2
      - trino3
    environment:
      - DB_URL=postgres://trino_proxy:trino_proxy@postgres/trino_proxy
      - HTTP_ENABLED=true
      - LOG_LEVEL=debug
      - NODE_ENV=production
      - ROUTING_METHOD=LOAD
      - ENABLE_SCHEDULER=true

  postgres:
    image: postgres:13
    container_name: postgres
    restart: always
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: trino_proxy
      POSTGRES_PASSWORD: trino_proxy
      POSTGRES_DB: trino_proxy

  trino1:
    image: trinodb/trino
    container_name: trino1
    restart: always
    volumes:
      - ./seeds/trino_config:/etc/trino
    depends_on:
      - postgres
    ports:
      - 8091:8080

  trino2:
    image: trinodb/trino
    container_name: trino2
    restart: always
    volumes:
      - ./seeds/trino_config:/etc/trino
    depends_on:
      - postgres
    ports:
      - 8092:8080

  trino3:
    image: trinodb/trino
    container_name: trino3
    restart: always
    volumes:
      - ./seeds/trino_config:/etc/trino
    depends_on:
      - postgres
    ports:
      - 8093:8080
