version: "3.7"

services:
  proxy:
    build: .
    restart: always
    volumes:
      - ./migrations:/app/migrations
      - ./seeds:/app/seeds
      - ./src:/app/src
    ports:
      - 8080:8080
    depends_on:
      - postgres
      - trino
    environment:
      - DB_URL=postgres://trino_proxy:trino_proxy@postgres/trino_proxy
      - HTTP_ENABLED=true
      - LOG_LEVEL=info
      - NODE_ENV=production
      - RESULT_SET_ROW_LIMIT=500
      - RESULT_SET_ROW_LIMIT_CLIENT_TAG=mode

  postgres:
    image: postgres:13
    restart: always
    ports:
      - 8082:5432
    environment:
      POSTGRES_USER: trino_proxy
      POSTGRES_PASSWORD: trino_proxy
      POSTGRES_DB: trino_proxy

  trino:
    image: trinodb/trino
    restart: always
    ports:
      - 8081:8080
