version: "3.7"

services:
  proxy:
    build: .
    container_name: trino-proxy
    restart: always
    volumes:
      - ./src:/app/src
    ports:
      - 8080:8080
    depends_on:
      - postgres
    environment:
      - LOG_LEVEL=debug
      - NODE_ENV=production
      - DB_URL=postgres://trino_proxy:trino_proxy@postgres/trino_proxy

  postgres:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: trino_proxy
      POSTGRES_PASSWORD: trino_proxy
      POSTGRES_DB: trino_proxy
